name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.3

      - name: Generate Gradle Wrapper
        run: gradle wrapper

      - name: Build APK
        run: ./gradlew assembleDebug --info

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: myapp-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
